/*TABLE CUSTOMER*/
CREATE TABLE CUSTOMER(
					CUST_ID INT,
					USER_AUTHORITY VARCHAR2(45),
					USERNAME 		VARCHAR2(45),
					PASSWORD		NUMBER(20)，
					FIRST_NAME		VARCHAR2(45),
					LAST_NAME		VARCHAR2(45),
					EMAIL			VARCHAR2(45),
					ADDRESS			VARCHAR2(45),
					PHONE_NUMBER	NUMBER(20),
					CONSTRAINT CUST_ID_PK PRIMARY KEY(CUST_ID));
					
/*TABLE RESTAURANT*/
CREATE TABLE RESTAURANT (
					REST_ID				INT,
					REST_CATEGORY_ID	NUMBER(6),
					REST_NAME			VARCHAR2(45),
					REST_ADD			VARCHAR2(45),
					REST_DESC			VARCHAR2(45),
					REST_PHONE			NUMBER(20),
					REST_PIC_FILE		NUMBER(6),
					CONSTRAINT REST_ID_PK PRIMARY KEY(REST_ID));
					
/*TABLE ORDER*/
CREATE TABLE ORDERS (
					ORDER_NUMBER INT,
					ORDER_STATUS VARCHAR2(45)，
					PAYMENT_DATE DATE,
					CUST_ID		 INT,
					REST_ID		 INT,
					CONSTRAINT ORDER_NUMBER_PK PRIMARY KEY(ORDER_NUMBER));
ALTER TABLE ORDERS
ADD CONSTRAINT CUST_ID_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID);
ALTER TABLE ORDERS
ADD CONSTRAINT REST_ID_FK FOREIGN KEY (REST_ID) REFERENCES RESTAURANT (REST_ID);

/*TABLE SOLD_PRODUCT*/
CREATE TABLE SOLD_PRODUCT (
					ORDER_NUMBER INT,
					PRODUCT_ID   INT,
					QUANITY		 VARCHAR2(45),
					RATE_POINT	 NUMBER(5),
					REVIEW		 VARCHAR2(45),
					CONSTRAINT ORDER_NUMBER_PRODUCT_ID PRIMARY KEY(ORDER_NUMBER, PRODUCT_ID)）;
					
/*TABLE PRODUCT*/
CREATE TABLE PRODUCT (
					PRODUCT_ID 		INT,
					PRODUCT_NAME	VARCHAR2(45),
					PRODUCT_PRICE	DECIMAL(3,2),
					PIC_FILE		VARCHAR2(45),
					CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID));
					
/*TABLE CODE*/
CREATE TABLE CODE (
					TABLENAME 		VARCHAR2(45),
					COLNAME 		VARCHAR2(45),
					CODE_VALUE 		VARCHAR2(45),
					DESCRIPTION		VARCHAR2(45),
					CONSTRAINT TN_CO_COV_PK PRIMARY KEY (TABLENAME, COLNAME, CODE_VALUE));
					
/*SEQUENCE FOR CUSTOMER*/
CREATE SEQUENCE CUSTOMER_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 9999
	NOCYCLE;
	









					
					
					
					